# Generated by Django 5.1.2 on 2024-10-30 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('mobile', models.IntegerField(null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('created_time', models.TimeField(auto_now_add=True)),
                ('updated_time', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_member_arrival_and_left_time_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.TimeField(null=True)),
                ('left_time', models.TimeField(null=True)),
                ('public_ip', models.CharField(max_length=255, null=True)),
                ('private_ip', models.CharField(max_length=255, null=True)),
                ('country_code', models.CharField(max_length=255, null=True)),
                ('country_name', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('postal', models.CharField(max_length=255, null=True)),
                ('latitude', models.CharField(max_length=255, null=True)),
                ('longitude', models.CharField(max_length=255, null=True)),
                ('ip_type', models.CharField(max_length=255, null=True)),
                ('state', models.CharField(max_length=255, null=True)),
                ('current_machine_id', models.TextField(null=True)),
                ('login_status', models.CharField(max_length=255, null=True)),
                ('login_system_ip_address', models.CharField(max_length=255, null=True)),
                ('login_system_name', models.CharField(max_length=255, null=True)),
                ('dt', models.DateField(auto_now_add=True)),
                ('tm', models.TimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=255, null=True)),
                ('emp_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_arrival_and_left_time_details_member_id', to='LogApp.tbl_employees')),
            ],
        ),
    ]
