# Generated by Django 5.1.2 on 2024-11-05 10:16

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogApp', '0002_tbl_employees_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdleSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('idle_start', models.DateTimeField()),
                ('idle_end', models.DateTimeField()),
                ('total_idle_time', models.DurationField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LogApp.tbl_employees')),
            ],
        ),
    ]
