# Generated by Django 5.1.2 on 2024-11-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogApp', '0003_idlesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_employees',
            name='joining_date',
            field=models.DateField(null=True),
        ),
    ]
