# Generated by Django 5.1.2 on 2024-11-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogApp', '0004_tbl_employees_joining_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='idlesession',
            name='reason',
            field=models.TextField(null=True),
        ),
    ]
