# Generated by Django 5.1.2 on 2024-11-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogApp', '0005_idlesession_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_member_arrival_and_left_time_details',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_member_arrival_and_left_time_details',
            name='left_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
