# Generated by Django 5.1.2 on 2024-11-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogApp', '0006_alter_tbl_member_arrival_and_left_time_details_arrival_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_employees',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='tbl_employees',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
