# Generated by Django 5.1.2 on 2024-11-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogApp', '0007_tbl_employees_end_time_tbl_employees_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_employees',
            name='user_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
