# Generated by Django 5.1.2 on 2024-11-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogApp', '0008_tbl_employees_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_employees',
            name='user_type',
        ),
        migrations.AddField(
            model_name='tbl_member_arrival_and_left_time_details',
            name='arrival_status',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tbl_member_arrival_and_left_time_details',
            name='left_status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
